swagger: '2.0'
info:
  title: REST AdditionalData SpamExpert API
  version: 1.0.0-beta
host: api.openprovider.eu
schemes:
- https
consumes:
- application/json
produces:
- application/json
security:
- Bearer: []
tags:
- name: SpamExpert
paths:
  /v1beta/spam-expert/generate-login-url:
    post:
      tags:
      - SpamExpert
      summary: Generate login url
      operationId: GenerateLoginURL
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/spam_expertGenerateLoginURLRequest'
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/spam_expertGenerateLoginURLResponse'
        default:
          description: (empty)
          schema:
            $ref: '#/definitions/errorError'
definitions:
  spam_expertGenerateLoginURLRequest:
    type: object
    title: GenerateLoginURLRequest
    properties:
      bundle:
        description: If you use the new, individually purchased, filters then set this to false. If you use the old bundled variant, then set this to true.
        type: boolean
        format: boolean
      domain_or_email:
        type: string
        title: Domain or email connected with the spam filter
    example:
      bundle: false
      domain_or_email: example.com
  spam_expertGenerateLoginURLResponse:
    type: object
    title: GenerateLoginURLResponse
    properties:
      code:
        type: integer
        format: int32
        title: Response code
      data:
        title: Response data
        $ref: '#/definitions/spam_expertGenerateLoginURLResponseData'
      desc:
        type: string
        title: Response description
      maintenance:
        type: boolean
        format: boolean
        title: Indicates if Openprovider API is on maintenance
      warnings:
        type: array
        title: Array of warning messages
        items:
          $ref: '#/definitions/errorWarning'
    example:
      code: 0
      data:
        url: http://spamexperts.example.com//?authticket=fdsaffdkaj3432fjkfjdslkjflk345435433fdfe
      desc: ''
  errorError:
    type: object
    title: Error
    properties:
      code:
        type: integer
        format: int32
        title: Error code
      data:
        type: string
        title: Additional error description
      desc:
        type: string
        title: Error description
    example:
      code: 0
      data: ''
      desc: ''
  errorWarning:
    type: object
    title: Warning
    properties:
      code:
        type: integer
        format: int32
        title: Warning code
      data:
        type: string
        title: Additional warning description
      desc:
        type: string
        title: Warning description
    example:
      code: 0
      data: ''
      desc: ''
  spam_expertGenerateLoginURLResponseData:
    type: object
    title: GenerateLoginURLResponseData
    properties:
      url:
        type: string
        title: An url that can be used for logging in to the SpamExperts control panel. If you want you can whitelabel the hostname by taking the auth at the end of the URL and replacing the part in front of it by your own URL, as long as it leads to our platform via DNS
    example:
      url: http://spamexperts.example.com//?authticket=fdsaffdkaj3432fjkfjdslkjflk345435433fdfe
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    x-linkTo: tag/descAuthentication
x-tagGroups:
- name: Introduction
  tags:
  - descAbout
  - descGettingStarted
  - descEndpoints
  - descAuthentication
- name: Quick Start
  tags:
  - descCustomerQuickstart
  - descDomainQuickstart
  - descTLDQuickstart
  - descDNSQuickstart
  - descSSLQuickstart
- name: Auth
  tags:
  - Auth
  - SpamExpert
- name: Billing
  tags:
  - InvoiceService
  - Payment
  - Transaction
- name: DNS
  tags:
  - DomainToken
  - NameserverService
  - NsGroupService
  - TemplateService
  - ZoneService
  - ZoneRecordService
- name: Domain
  tags:
  - DomainService
  - AdditionalData
  - CustomerAdditionalData
  - DomainPriceService
  - AuthCode
  - TldService
- name: EasyDmarc
  tags:
  - EasydmarcOrder
- name: Email template
  tags:
  - Email
- name: License
  tags:
  - LicenseService
- name: Reseller/Customer
  tags:
  - ContactService
  - Customer
  - EmailVerification
  - ResellerService
  - Settings
  - Statistics
  - TagService
- name: Spam Experts
  tags:
  - SEDomain
- name: SSL
  tags:
  - ApproverEmail
  - Csr
  - Order
  - OrderApproverEmail
  - OtpToken
  - Product
