openapi: 3.2.0
info:
  title: REST Email Verification API
  version: 1.0.0-beta
servers:
- url: https://api.openprovider.eu
security:
- Bearer: []
tags:
- name: Email Verification
paths:
  /v1beta/customers/verifications/emails/domains:
    get:
      tags:
      - Email Verification
      summary: List domain email verifications
      operationId: ListDomainEmailVerifications
      parameters:
      - description: The domain id.
        name: domain_id
        in: query
        schema:
          type: integer
          format: int32
      - description: The domain.
        name: domain
        in: query
        schema:
          type: string
      - description: The email.
        name: email
        in: query
        schema:
          type: string
      - description: The handle.
        name: handle
        in: query
        schema:
          type: string
      - description: The status.
        name: status
        in: query
        schema:
          type: string
      - description: The description.
        name: description
        in: query
        schema:
          type: string
      - description: Is suspended.
        name: is_suspended
        in: query
        schema:
          type: boolean
          format: boolean
      - description: The type.
        name: response.type
        in: query
        schema:
          type: string
      - description: The to.
        name: response.to
        in: query
        schema:
          type: string
      - description: The limit.
        name: limit
        in: query
        schema:
          type: integer
          format: int32
      - description: The offset.
        name: offset
        in: query
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emailListDomainVerificationsResponse'
        default:
          description: (empty)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorError'
  /v1beta/customers/verifications/emails/restart:
    post:
      tags:
      - Email Verification
      summary: Restart email verification
      operationId: RestartEmailVerification
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emailRestartEmailVerificationResponse'
        default:
          description: (empty)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailRestartEmailVerificationRequest'
        required: true
  /v1beta/customers/verifications/emails/start:
    post:
      tags:
      - Email Verification
      summary: Start email verification
      operationId: StartEmailVerification
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emailStartEmailVerificationResponse'
        default:
          description: (empty)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailStartEmailVerificationRequest'
        required: true
components:
  schemas:
    emailListDomainVerificationsResponse:
      type: object
      title: ListDomainVerificationsResponse
      properties:
        code:
          type: integer
          format: int32
          title: The code
        data:
          title: The data
          $ref: '#/components/schemas/emailListDomainVerificationsResponseData'
        desc:
          type: string
          title: The desc
        maintenance:
          type: boolean
          format: boolean
          title: The maintenance
        warnings:
          type: array
          title: The warnings
          items:
            $ref: '#/components/schemas/errorWarning'
      example:
        code: 0
        data:
          results:
          - description: ''
            domain: ''
            email: ''
            expiration_date: ''
            handle: ''
            is_suspended: false
            status: ''
          total: 0
        desc: ''
    errorWarning:
      type: object
      title: Warning
      properties:
        code:
          type: integer
          format: int32
          title: Warning code
        data:
          type: string
          title: Additional warning description
        desc:
          type: string
          title: Warning description
      example:
        code: 0
        data: ''
        desc: ''
    emailStartEmailVerificationRequest:
      type: object
      title: StartEmailVerificationRequest
      properties:
        email:
          type: string
          title: Email address
        handle:
          type: string
          title: Customer's handle
        language:
          type: string
          title: The language
        tag:
          type: string
          title: The tag
      example:
        email: test@mail.tld
        handle: ''
        language: ''
        tag: ''
    emailRestartEmailVerificationResponseData:
      type: object
      title: RestartEmailVerificationResponseData
      properties:
        success:
          type: boolean
          format: boolean
          title: Indicates if operation was successful
      example:
        success: false
    errorError:
      type: object
      title: Error
      properties:
        code:
          type: integer
          format: int32
          title: Error code
        data:
          type: string
          title: Additional error description
        desc:
          type: string
          title: Error description
      example:
        code: 0
        data: ''
        desc: ''
    emailStartEmailVerificationResponse:
      type: object
      title: StartEmailVerificationResponse
      properties:
        code:
          type: integer
          format: int32
          title: Response code
        data:
          title: Response data
          $ref: '#/components/schemas/emailStartEmailVerificationResponseData'
        desc:
          type: string
          title: Response description
        maintenance:
          type: boolean
          format: boolean
          title: Indicates if Openprovider API is on maintenance
        warnings:
          type: array
          title: Array of warning messages
          items:
            $ref: '#/components/schemas/errorWarning'
      example:
        code: 20001
        data:
          id: 123456789
        desc: Verification email in progress
    emailStartEmailVerificationResponseData:
      type: object
      title: StartEmailVerificationResponseData
      properties:
        id:
          type: integer
          format: int32
          title: Object ID
      example:
        id: 123456789
    emailListDomainVerificationsResponseData:
      type: object
      title: ListDomainVerificationsResponseData
      properties:
        results:
          type: array
          title: The results
          items:
            $ref: '#/components/schemas/emailDomainEmailVerification'
        total:
          type: integer
          format: int32
          title: The total
      example:
        results:
        - description: ''
          domain: ''
          email: ''
          expiration_date: ''
          handle: ''
          is_suspended: false
          status: ''
        total: 0
    emailRestartEmailVerificationResponse:
      type: object
      title: RestartEmailVerificationResponse
      properties:
        code:
          type: integer
          format: int32
          title: Response code
        data:
          title: Response data
          $ref: '#/components/schemas/emailRestartEmailVerificationResponseData'
        desc:
          type: string
          title: Response description
        maintenance:
          type: boolean
          format: boolean
          title: Indicates if Openprovider API is on maintenance
        warnings:
          type: array
          title: Array of warning messages
          items:
            $ref: '#/components/schemas/errorWarning'
      example:
        code: 0
        data:
          success: false
        desc: ''
    emailDomainEmailVerification:
      type: object
      title: DomainEmailVerification
      properties:
        description:
          type: string
          title: The description
        domain:
          type: string
          title: The domain
        email:
          type: string
          title: The email
        expiration_date:
          type: string
          title: The expiration date
        handle:
          type: string
          title: The handle
        is_suspended:
          type: boolean
          format: boolean
          title: Is suspended
        status:
          type: string
          title: The status
      example:
        description: ''
        domain: ''
        email: ''
        expiration_date: ''
        handle: ''
        is_suspended: false
        status: ''
    emailRestartEmailVerificationRequest:
      type: object
      title: RestartEmailVerificationRequest
      properties:
        email:
          type: string
          title: Email address
        language:
          type: string
          title: The language
        tag:
          type: string
          title: The tag
      example:
        email: test@mail.tld
        language: ''
        tag: ''
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      x-linkTo: tag/descAuthentication
x-tagGroups:
- name: Introduction
  tags:
  - descAbout
  - descGettingStarted
  - descEndpoints
  - descAuthentication
- name: Quick Start
  tags:
  - descCustomerQuickstart
  - descDomainQuickstart
  - descTLDQuickstart
  - descDNSQuickstart
  - descSSLQuickstart
- name: Auth
  tags:
  - Auth
  - SpamExpert
- name: Billing
  tags:
  - InvoiceService
  - Payment
  - Transaction
- name: DNS
  tags:
  - DomainToken
  - NameserverService
  - NsGroupService
  - TemplateService
  - ZoneService
  - ZoneRecordService
- name: Domain
  tags:
  - DomainService
  - AdditionalData
  - CustomerAdditionalData
  - DomainPriceService
  - AuthCode
  - TldService
- name: EasyDmarc
  tags:
  - EasydmarcOrder
- name: Email template
  tags:
  - Email
- name: License
  tags:
  - LicenseService
- name: Reseller/Customer
  tags:
  - ContactService
  - Customer
  - EmailVerification
  - ResellerService
  - Settings
  - Statistics
  - TagService
- name: Spam Experts
  tags:
  - SEDomain
- name: SSL
  tags:
  - ApproverEmail
  - Csr
  - Order
  - OrderApproverEmail
  - OtpToken
  - Product
